### ISSUE TITLE
Depth Level

### ISSUE THREAD

**Issue by hiroaki-yamamoto** [hiroaki-yamamoto/omm#15]
Suppose that there'are 3 class and target objects:

`class`
```python
class User(omm.Mapper):
    name = omm.MapField("test.name")
    age = omm.MapField("test.age", get_cast=int, set_cast=int)
    gender = omm.MapField("test.gender")


class Article(omm.Mapper):
    publisher = omm.MapField(User)
    year = omm.MapField("publish.year", get_cast=int, set_cast=int)


class IndexModel(omm.Mapper):
    user = omm.MapField(User)
    article = omm.MapField(Article)
```

`object (assume obj)`
```YaML
test:
    name: Test Example
    age: 25
    gender: test
publish:
    year: 2016
```

The result of `IndexModel(obj).dumps(yaml.dumps)` should be:

```YaML
user:
    name: Test Example
    age: 25
    gender: test
article:
    publisher:
        name: Test Example
        age: 25
        gender: test
    year: 2016
```

Note that `Article.publisher` is `IndexModel.user`. Therefore, change the either field, the other field should be changed.
(And I can't image the use case of this feature... unfortunately)
